#pragma once
#include "order.hpp"
#include "pricelevel.hpp"
#include "orderpool.hpp"
#include <vector>
#include <unordered_map>
#include <optional>
#include <cstdint>


struct Fill{
    uint64_t incoming_order_id;
    uint64_t resting_order_id;
    uint64_t price;
    uint32_t qty;
   
};

// fixed_price_range limit order book with ptice time priority

class OrderBook {
    public:
    OrderBook(uint64_t min_price, uint64_t max_price, size_t order_pool_capacity);
    // fills and matches the matching order; the remaining is resting in the book
    // and this returns the fills generated by this call
    std::vector<Fill> add_limit_order(uint64_t order_id, Side side, uint64_t price, uint32_t qty);

    bool cancel_order(uint64_t order_id);

    std::optional<uint64_t> best_bid_price() const;
    std::optional<uint64_t> best_ask_price() const;

    size_t resting_order_count() const { return id_to_order_.size(); }
    size_t pool_available() const { return pool_.available(); }

private:
    uint64_t min_price_;
    uint64_t max_price_;
    size_t levels_count_;
 
    std::vector<PriceLevel> bids_;
    std::vector<PriceLevel> asks_;
    std::vector<uint64_t> bid_bitmap_;
    std::vector<uint64_t> ask_bitmap_;
 
    OrderPool pool_;
    std::unordered_map<uint64_t, Order*> id_to_order_;
    uint64_t sequence_ = 0;

    int64_t best_bid_idx_ = -1;  // -1 == no bids resting
    int64_t best_ask_idx_ = -1;  // -1 == no asks resting
 
    inline size_t price_to_index(uint64_t price) const { return static_cast<size_t>(price - min_price_); }
    inline uint64_t index_to_price(int64_t idx) const { return min_price_ + static_cast<uint64_t>(idx); }
 
    static void set_bit(std::vector<uint64_t>& bm, size_t idx);
    static void clear_bit(std::vector<uint64_t>& bm, size_t idx);
 
    // Highest set bit at or below from_idx, or -1 if none (used for bids:
    // higher index == higher price == better bid).
    int64_t find_highest_set(const std::vector<uint64_t>& bm, int64_t from_idx) const;
 
    // Lowest set bit at or above from_idx, or -1 if none (used for asks:
    // lower index == lower price == better ask).
    int64_t find_lowest_set(const std::vector<uint64_t>& bm, int64_t from_idx) const;
};




 